### ISSUE TITLE
[] and []<- methods for NLworldMatrix

### ISSUE THREAD

**Issue by SarahBauduin** [PredictiveEcology/NetLogoR#11]
If `world` is a NLworldMatrix object, `world[0,0]` does not use the method `[]` defined for NLworldMatrix object, it uses the method for the matrix and therefore `world[0,0]` does not work.

**Comment by eliotmcintire** [comment]
Hmm. This may be the same problem I have been having with agentMatrix
class. It may mean it needs to be an S4 class object.

**Comment by SarahBauduin** [comment]
Because there are the functions of() and set() to access and change values of the world, I don't think we need [] and []<- to work on NLworldMatrix

**Comment by SarahBauduin** [comment]
Solved by changing the NLworldMatrix and NLworldArray objects into S4 objects
