### ISSUE TITLE
To do list

### ISSUE THREAD

**Issue by eliotmcintire** [PredictiveEcology/NetLogoR#13]
- [x] Clean up unused stub classes (`SpatialPointsDataTable`, `agentDataTable`)
- [x] Make examples throughout for `agentMatrix` and `NLworldMs` classes

- [ ] rename 3 new classes.  Possibilities:
    
    - [ ] `agentMatrix` -->  `turtles` or `spdf2` or `agent` or ...
    - [x] `NLworldMatrix` --> `world` or `Raster2` or `layer` or ...
    - [x] `NLworldArray` --> `worlds` or `RasterStack2` or `layers` or ...

- [ ] Plot method for

    - [x] `NLworldMatrix` - Done in SpaDES commit c358e55
    - [ ] `NLworldArray`
    - [x] `agentMatrix` - Done in SpaDES commit c358e55

- [x] Do some more testings for the converting functions
- [x] Update function documentation and examples
- [x] Update programming guide (see also #15)
- [x] Update dictionary

- [x] Run Travis without error
- [x] Add tests to complete coverage

**Comment by SarahBauduin** [comment]
- Do some more testings for the converting functions
- Plot functions for new classes
- Update function documentation and examples
- Update programming guide
- Update dictionary

**Comment by SarahBauduin** [comment]
I completed the coverage except for the agentMatrix that I leave to you (and that will be taken out of NetLogoR)
Most likely "agentMatrix" won't be renamed.
Making plot functions will be put as a separate issue as it is more SpaDES related than NetLogoR related.
