### ISSUE TITLE
remove 'microbenchmark' package from examples?

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/NetLogoR#20]
is it necessary for the user, or was `microbenchmark` simply used for our development/testing purposes? if so, then it should be removed from examples and as a dependency (Suggests)

**Comment by eliotmcintire** [comment]
It was to show an example of how the agentMatrix is faster than the SPDF. I have wrapped it in an 
`if(require(microbenchmark))` , which is the correct thing to do, and add it to Suggests
594aecc3d627f2230e9062e943480439b29a6b64
