### ISSUE TITLE
Functions without parameters

### ISSUE THREAD

**Issue by SarahBauduin** [PredictiveEcology/NetLogoR#22]
What to do with the documentation for `noPatches()` and `noTurtles() `?

They do not require parameters to be supplied but at least one argument is needed for S4 methods.
With `x` as an argument and a signature "missing", the documentation still shows `x` as a parameter to fill.

**Comment by achubaty** [comment]
I don't see this as a problem. It's perhaps a bit weird or annoying, but if the documentation is clear that `x` should not be supplied (it's ignored anyway) then hopefully that's clear enough. Besides, anyone coming from the netlogo world (ha! see what I did there?) will be used to not supplying an argument to these functions.

**Comment by eliotmcintire** [comment]
Did anyone try a non-S4 approach... does Travis balk if it is "just a
function"?  And does Alex balk if it is "just a function".  We could
certainly also do an S3 method (again does Travis and Alex balk?). They
might work on Travis because there is not the whole signature issue.

Elito

**Comment by achubaty** [comment]
@eliotmcintire the issue isn't travis. Sarah balks at a help file containing param x with decription "not used"

**Comment by eliotmcintire** [comment]
I think it is deeper than that. Having an argument that is not used is a
pretty shoddy function. The only reason it would be there would be appease
Travis, which seems pretty esoteric for the average R user ( a conversation
in the head of an average R user ... type: ?noTurtles ... "what is this x
argument?"... "not used"... "how stupid is that"... )

So, to clean up the function, it may be better to have an S3 class or just
a function. But that "breaks" the purity of the S4 classes throughout.
Since many other packages, including R itself, mix S4 and S3, I am ok with
mixing.

The question is, will Travis still require an argument, even though there
isn't one. Or is it just an S4 issue that Travis has.

**Comment by achubaty** [comment]
Just a point of clarification that this isn't a Travis issue, but a
requirement of the S4 approach which is enforced during R CMD check.

I agree it's weird to have to declare an unused argument especially when
this is the only method for this function. I do y have a problem with using S3
here.


On Monday, 20 June 2016, Eliot McIntire <notifications@github.com> wrote:

> I think it is deeper than that. Having an argument that is not used is a
> pretty shoddy function. The only reason it would be there would be appease
> Travis, which seems pretty esoteric for the average R user ( a conversation
> in the head of an average R user ... type: ?noTurtles ... "what is this x
> argument?"... "not used"... "how stupid is that"... )
>
> So, to clean up the function, it may be better to have an S3 class or just
> a function. But that "breaks" the purity of the S4 classes throughout.
> Since many other packages, including R itself, mix S4 and S3, I am ok with
> mixing.
>
> The question is, will Travis still require an argument, even though there
> isn't one. Or is it just an S4 issue that Travis has.
>
>
>
> On Mon, Jun 20, 2016 at 10:14 AM, Alex Chubaty <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > @eliotmcintire <https://github.com/eliotmcintire> the issue isn't
> travis.
> > Sarah balks at a help file containing param x with decription "not used"
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/PredictiveEcology/NetLogoR/issues/22#issuecomment-227207188
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ABDK2860AXMqwtURjV4u04YwlOx-dxfBks5qNspYgaJpZM4I5q9V
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/PredictiveEcology/NetLogoR/issues/22#issuecomment-227216951>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADRsOfVqgZMleMH_ajeB1d67BmsniWcfks5qNtLMgaJpZM4I5q9V>
> .
>


-- 
--
Alex M. Chubaty, PhD

Postdoctoral Researcher, Canadian Forest Service
Natural Resources Canada / Government of Canada
alexander.chubaty@canada.ca / Tel: 250-298-2347

Stagiaire postdoctoral (recherche), Service canadien des forêts
Ressources naturelles Canada / Gouvernement du Canada
alexander.chubaty@canada.ca / Tél: 250-298-2347

**Comment by eliotmcintire** [comment]
The key part of your sentence was typo muddled. Did you say "do" or "don't"
have a problem?

**Comment by achubaty** [comment]
Argh, autocorrect. I *do not* have a problem with S3 for those functions.

On Monday, 20 June 2016, Eliot McIntire <notifications@github.com> wrote:

> The key part of your sentence was typo muddled. Did you say "do" or "don't"
> have a problem?
>
> On Mon, Jun 20, 2016 at 11:38 AM, Alex Chubaty <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>>
> wrote:
>
> > Just a point of clarification that this isn't a Travis issue, but a
> > requirement of the S4 approach which is enforced during R CMD check.
> >
> > I agree it's weird to have to declare an unused argument especially when
> > this is the only method for this function. I do y have a problem with
> > using S3
> > here.
> >
> >
> > On Monday, 20 June 2016, Eliot McIntire <notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>> wrote:
> >
> > > I think it is deeper than that. Having an argument that is not used is
> a
> > > pretty shoddy function. The only reason it would be there would be
> > appease
> > > Travis, which seems pretty esoteric for the average R user ( a
> > conversation
> > > in the head of an average R user ... type: ?noTurtles ... "what is
> this x
> > > argument?"... "not used"... "how stupid is that"... )
> > >
> > > So, to clean up the function, it may be better to have an S3 class or
> > just
> > > a function. But that "breaks" the purity of the S4 classes throughout.
> > > Since many other packages, including R itself, mix S4 and S3, I am ok
> > with
> > > mixing.
> > >
> > > The question is, will Travis still require an argument, even though
> there
> > > isn't one. Or is it just an S4 issue that Travis has.
> > >
> > >
> > >
> > > On Mon, Jun 20, 2016 at 10:14 AM, Alex Chubaty <
> notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>
> > > <javascript:_e(%7B%7D,'cvml','notifications@github.com
> <javascript:_e(%7B%7D,'cvml','notifications@github.com');>');>>
> > > wrote:
> > >
> > > > @eliotmcintire <https://github.com/eliotmcintire> the issue isn't
> > > travis.
> > > > Sarah balks at a help file containing param x with decription "not
> > used"
> > > >
> > > > —
> > > > You are receiving this because you were mentioned.
> > > > Reply to this email directly, view it on GitHub
> > > > <
> > >
> >
> https://github.com/PredictiveEcology/NetLogoR/issues/22#issuecomment-227207188
> > > >,
> > > > or mute the thread
> > > > <
> > >
> >
> https://github.com/notifications/unsubscribe/ABDK2860AXMqwtURjV4u04YwlOx-dxfBks5qNspYgaJpZM4I5q9V
> > > >
> > > > .
> > > >
> > >
> > > —
> > > You are receiving this because you commented.
> > > Reply to this email directly, view it on GitHub
> > > <
> >
> https://github.com/PredictiveEcology/NetLogoR/issues/22#issuecomment-227216951
> > >,
> > > or mute the thread
> > > <
> >
> https://github.com/notifications/unsubscribe/ADRsOfVqgZMleMH_ajeB1d67BmsniWcfks5qNtLMgaJpZM4I5q9V
> > >
> > > .
> > >
> >
> >
> > --
> > --
> > Alex M. Chubaty, PhD
> >
> > Postdoctoral Researcher, Canadian Forest Service
> > Natural Resources Canada / Government of Canada
> > alexander.chubaty@canada.ca
> <javascript:_e(%7B%7D,'cvml','alexander.chubaty@canada.ca');> / Tel:
> 250-298-2347
> >
> > Stagiaire postdoctoral (recherche), Service canadien des forêts
> > Ressources naturelles Canada / Gouvernement du Canada
> > alexander.chubaty@canada.ca
> <javascript:_e(%7B%7D,'cvml','alexander.chubaty@canada.ca');> / Tél:
> 250-298-2347
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <
> https://github.com/PredictiveEcology/NetLogoR/issues/22#issuecomment-227230662
> >,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/ABDK21V7KdvBJj2qEDPhkEaGmA8cN3bNks5qNt49gaJpZM4I5q9V
> >
> > .
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/PredictiveEcology/NetLogoR/issues/22#issuecomment-227234745>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADRsORZOE5YvQGxDXEBcrbRgK5eF6Wavks5qNuGlgaJpZM4I5q9V>
> .
>


-- 
--
Alex M. Chubaty, PhD

Postdoctoral Researcher, Canadian Forest Service
Natural Resources Canada / Government of Canada
alexander.chubaty@canada.ca / Tel: 250-298-2347

Stagiaire postdoctoral (recherche), Service canadien des forêts
Ressources naturelles Canada / Gouvernement du Canada
alexander.chubaty@canada.ca / Tél: 250-298-2347

**Comment by SarahBauduin** [comment]
noPatches() and noTurtles() done as S3 functions.
Run fine and the documentation doesn't have a parameter anymore
