### ISSUE TITLE
use inherits() instead of class() to check object class

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/NetLogoR#25]
*E.g.*, https://stackoverflow.com/q/27923345/1380598

**Comment by SarahBauduin** [comment]
Done :)

**Comment by achubaty** [comment]
done in b75cff6999e68cf4bc379f81e2394f660b914f1e

@SarahBauduin  please remember to link commits to to their issues. In the commit message you can add the issue number, *e.g.*, "resolves #25"
