### ISSUE TITLE
`plot` methods for NetLogoR classes

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/NetLogoR#27]
@SarahBauduin I've been going through the MS and examples, and I'm wondering why the user needs to use `turtles2spdf()` when they want to plot their turtles. Can we simply provide a plot method to do this internally so the user doesn't need to think about it?

**Comment by SarahBauduin** [comment]
I wrote the MS before we made the recent plot methods for all the classes so this part needs to be changed. If you look at the code example, I already changed it and I only used "points(t1)" without converting it before to a spdf.

**Comment by achubaty** [comment]
OK, great. I haven't looked closely at the code yet. I will update that part of the MS.
