### ISSUE TITLE
cleanup help docs to reduce spelling false-positives

### ISSUE THREAD

**Issue by achubaty** [PredictiveEcology/NetLogoR#34]
`devtools::spell_check()` reveals many false-positives, which can probably be reduced by ensure that code is wrapped in `\code{}` blocks in all help files.

**Comment by SarahBauduin** [comment]
Done in commit d0e8a79
Can someone check if I fixed all the false positives.
For example, what to do with the URL in the reference section? Do I use `\url{}` ?
And should the word "NetLogo" be inside `\code{}`?

**Comment by achubaty** [comment]
yes, urls are generally put in `\url{}`. "NetLogo" is probably fine as is -- we can add that to the list of allowed words
