### ISSUE TITLE
raster2world very slow

### ISSUE THREAD

**Issue by SarahBauduin** [PredictiveEcology/NetLogoR#38]
This function is slow
```
r1 <- raster(extent(c(0, 20000, 0, 20000)), nrows = 100, ncols = 100)
res(r1) <- 200
r1[]<-runif(100)
r_land <- raster2world(r1, method = "ngb")
```
Why not use something like `r_land <- createWorld(1, r1@ncols, 1, r1@nrows, data = r1[])` inside the function `raster2world()` instead of using the function `resample()` (which is the slow part I guess)

**Comment by eliotmcintire** [comment]
Seems like that would be fine. I don't recall if there was a good reason for `resample()` or it was just a decent solution.

**Comment by SarahBauduin** [comment]
I did a few tests and the proposed solution doesn't work when the resolution is not equal to 1. Maybe we can find another way to do the resample without using the function resample() which is slow.

**Comment by eliotmcintire** [comment]
Put in a test for resolution equals 1,if yes, use fast, if no use resample.

**Comment by SarahBauduin** [comment]
Hi Alex,
I didn't have time to work on this and I won't have time in the near future.
As a few people contacting me because NetLogoR is not available and there is the workshop I'll give on IBM and NetLogoR in two weeks, I would say to submit the package like this.
I'll try to work on something (if I can) during the summer.
Thanks!

Sarah

________________________________
De : Alex Chubaty ***@***.***>
Envoyé : jeudi 10 juin 2021 20:41
À : PredictiveEcology/NetLogoR ***@***.***>
Cc : Sarah Bauduin ***@***.***>; Author ***@***.***>
Objet : Re: [PredictiveEcology/NetLogoR] raster2world very slow (#38)


any update on this?

**Comment by achubaty** [comment]
sounds good, i'll submit today

**Comment by eliotmcintire** [comment]
@SarahBauduin Revisiting this... In you example above, what is the world that you want, a 1m resolution world or a 200m resolution world?  Recall, "world" doesn't have a resolution: it is always 1. So, my suspicion is that you want a world of 100 x 100 pixels, not this:
```
Browse[1]> worldRaster
class      : RasterLayer 
dimensions : 20001, 20001, 400040001  (nrow, ncol, ncell)
resolution : 1, 1  (x, y)
```
which is what this function is creating ... i.e., 20001 x 20001 pixels with 1m each...

_Please confirm that you want a 101 x 101 pixel world_ and not a 20001 x 200001 pixel world

**Comment by eliotmcintire** [comment]
I believe this function was actually incorrect before. Worlds have a 1 unit resolution always. What is not specified is the "units" of that 1x1. NetLogo, I believe, did not start with a "real planet Earth" world, so 1 unit could be "100m" or "5km" or whatever. In the example provided at the top of this issue, the resolution is 200m. The correct output of the `raster2world` is a 101 x 101 resolution world, which has a 1 unit resolution, but where each unit is 200m. This is a weird situation imposed by the fact that worlds always have 1 unit resolution. The incorrect output is a 1m resolution 400 million pixel world. That is both computationally prohibitive and an incorrect use of the information contained in the original 200m x 200m raster. If a user wants a 400 million pixel world, they can make a 400 million pixel raster.

**Comment by SarahBauduin** [comment]
Yes, in my example the point was to obtain a 100 * 100 pixel (i.e., patch) world (not a 101 * 101). The aim was to match the nrow and ncols of the raster, whatever the real unit is (it ends up to be 1 for the world). I don't understand why it produced a 20001 x 200001 pixel world ...
Thanks for fixing it.
I'll look at that and add some tests to be sure

**Comment by SarahBauduin** [comment]
It's confusing to convert a raster into a worldMatrix because, usually, in a raster, round coordinate values represent the edges of the raster cell, whereas for the worldMatrix, round coordintate values represent the patch center. [I made this test](https://github.com/PredictiveEcology/NetLogoR/commit/f568d2cdb3fb0867aec9574cfbefcb3fdb82281b) and I think the function should create a worldMatrix with the same nrows, ncols and values as in the original raster

**Comment by eliotmcintire** [comment]
I thought that we had always resulted in 1 extra row and column for the "worldMatrix/worldArray" because the coordinates are "center" of pixel. If we pick the "same" number of rows and columns, then the whole thing will be shifted.

**Comment by SarahBauduin** [comment]
You're right, we did add a col and a row to the worldMatrix. In the Details of the function, it is written : "The raster is resampled to match the coordinates system and resolution of a worldMatrix or worldArray using the chosen method. The extent will be bigger by 1 on the width and on the height.". 
The idea was to add 1/2 cell on all borders of the raster to create a new grid cell with the round values at the center of the patches (instead of the edges as in the raster). Then, we assign values to the patches using the ngb or bilinear method.
But I had the same thoughts as you when I created the test 2 days ago, because the actual coordinate values do not really matter in a worldMatrix, why do we add a new col and row and then reassign new values ? Can't we just take the grid as it is (nrow, ncol and values) from the raster, "shift" it of a 1/2 cell and "shift it" back of a 1/2 cell in the revert function.
However, I wonder how this will work when raster cells aren't square or when the "bilinear" method is chosen.
I think both thinking are correct, we just need to pick one.

**Comment by eliotmcintire** [comment]
I think we "pick" the one where we have the same number of pixels... so we do a "shift". This is essentially the same as "ngb", but without the need to create one column and one row of identical data to what is already there. If we were doing "bilinear", then it would be different, but I still think we should not be creating/modifying the input data. We just change the labels on the xcoord and ycoord, rather than do some unnecessary GIS. 

We will have to change the documentation and say that this is what we are doing... of course.

**Comment by SarahBauduin** [comment]
Ok, I agree.
I wonder why I made it so complicated back then ... I hope there wasn't a reason for it which I can't remember :)

**Comment by eliotmcintire** [comment]
Making a new issue...
