### ISSUE TITLE
Error with turtleSet() when merging more than 2 groups with different levels

### ISSUE THREAD

**Issue by SarahBauduin** [PredictiveEcology/NetLogoR#50]
When more than 2 groups need to be merged with `turtleSet()` the order is important and may create `NA` on character columns if the levels are different between the groups.
Example creating `NA`:
```
w1 <- createWorld(minPxcor = 0, maxPxcor = 4, minPycor = 0, maxPycor = 4, data = runif(25))
t1 <- createTurtles(n = 10, coords = randomXYcor(w1, n = 10))
t1 <- turtlesOwn(turtles = t1, tVar = "test", tVal = "a")
t2 <- NLwith(agents = t1, var = "who", val = 0:5)
t3 <- NLwith(agents = t1, var = "who", val = 6:7)
t4 <- NLwith(agents = t1, var = "who", val = 8:9)
t4 <- NLset(turtles = t4, agents = t4, var = "test", val = "b")
turtleSet(t2, t3, t4) # create NA instead of showing "b"
```
Doing `turtleSet(t2, turtleSet(t3,t4))` fix the problem.

The problem is with `levelsSame <- isTRUE(do.call(all.equal, lapply(dots, function(x) x@levels)))` in the `rbind` function which is used in `turtleSet()`.

I tried to fix it in the commit c00c080.
This didn't seem to fix the problem so I changed the `rbind` used in `turtleSet()` in the following commit 6477da9 but it still doesn't seem to fix the problem.

These two commits are in the development branch.

**Comment by achubaty** [comment]
Is this the source of the new failures on GitHub Actions?

```r
Error: Error in turtleSet(...) : object 'rbind.agentmatrix' not found
```

**Comment by achubaty** [comment]
@SarahBauduin the fix noted above seems to have resolved this. can you please confirm?

**Comment by SarahBauduin** [comment]
Thanks, I didn't see that spelling mistake.
It works but I don't understand why I had to change the `rbind` function name into `rbind.agentMatrix` for the function `turtleSet()` to work. Before, the function was `rbind` and it worked. If I updated the `rbind` function, why do I needed to put `rbind.agentMatrix` in `turtleSet()` instead of leaving `rbind`.
I don't quite understand what's happening.
Moreover, I'm sure there are other functions using `rbind` so I don't know if these functions will use the update `rbind` function.

**Comment by achubaty** [comment]
R should be doing the method dispatch for `rbind` to the `agentMatrix` class; you shouldn't need to specify this manually.

taking the examples from the tests, it appears to be dispatching correctly:

```r
d>   mat <- cbind(coords = matrix(1:6, ncol = 2), data.frame(
+     tmp = 1:3, tmp1 = 1:3,
+     tmp2 = c("e", "f", "g")
+   ))
d>   newAgent <- as(mat, "agentMatrix")
d>   mat <- cbind(coords = matrix(1:6, ncol = 2), data.frame(tmp = 1:3, tmp2 = c("e", "f", "g")))
d>   mat2 <- cbind(coords = matrix(1:6, ncol = 2), data.frame(tmp = 1:3, tmp2 = c("e", "f", "g")))
d>   newAgent1 <- as(mat, "agentMatrix")
d>   newAgent2 <- as(mat2, "agentMatrix")
d> 
d> sloop::s3_dispatch(rbind(newAgent1, newAgent2))
=> rbind.agentMatrix
   rbind.default
 * rbind (internal)
d> sloop::s3_dispatch(rbind(newAgent1[, 3], newAgent2[, 3]))
=> rbind.agentMatrix
   rbind.default
 * rbind (internal)
d> sloop::s3_dispatch(rbind(newAgent, newAgent1))
=> rbind.agentMatrix
   rbind.default
 * rbind (internal)
 ```
 
when I revert the change on that line in `turtleSet()` to use `rbind()`, it works. (also note that the `do.call` construction doesn't need the `lapply(dots, function(x) x)` because `dots` is already a list, so extracting the elements only to put them back in alist seems redundant).

**Comment by SarahBauduin** [comment]
Thanks Alex! That makes more sense.
Using only `rbind` didn't work when I tried it locally on my computer but I guess there's something in the package framework that makes it work. Perfect.
And thanks for the correction about `do.call`.
All good for me!
