### ISSUE TITLE
Clean or improve neighbors()

### ISSUE THREAD

**Issue by SarahBauduin** [PredictiveEcology/NetLogoR#9]
Function in NetLogoR/R/patch-functions.R

I cannot figure out how to obtain the same results as when I merge the df by using a merge on data.tables.
The second solution uses data.table but is wrong because if `torus = FALSE`, there isn't `nNeighbors` patches per agent so the `id  = rep(cellNum[,id], nNeighbors)` doesn't work. This solution also doesn't deal well with duplicate agents.

**Comment by eliotmcintire** [comment]
I did not see this issue before I pushed changes to the function. It now has both data.frame and data.table, with data.table working when there are >100 agents (that seems to be the cut point for speed). It is fast for lots of agents ... e.g., 100,000 or more. 

It passes all tests, so I believe it is equivalent, but perhaps it is not. Please make tests that would correctly test for the issue you point out here.

**Comment by SarahBauduin** [comment]
I added more tests and it works fine! 
It is super fast :)
